### PR TITLE
Allow the wallpaper mode to be selectively applied per screen/display

### PR DESCRIPTION
**Pull request by jdf221**
Only wanted to run this on my secondary screen so here it is.

Replaces the current "Launch Aerial as Wallpaper" item with a submenu that lists all screens detected. Clicking on them will toggle them on/off with a checkmark indicating it. Also saves which displays are enabled/disabled in preferences and automatically launches them when AerialCompanion starts. (Or at least when the MenuViewController `viewDidLoad()` is called)

image

Although when I run my build the wallpaper/instance is always just a constant grey. But launching it with the Launch item in the menu works fine. Not sure if I just don't have my stuff setup right or I broke it somehow...

Biggest change is DesktopLauncher no longer has a static instance. Instead it's `init` takes in a NSScreen with a default of NSScreen.main. MenuViewController has a Directory of `[ScreenUuid: DesktopLauncher]` and `MenuViewController.toggleDesktopLauncher(uuid)` handles the creation/usage of the DesktopLauncher instances as well as updating the preferences.

### CODE REVIEW

**Comment by glouel** [comment]
Hey @jdf221 !

This looks pretty good, thanks a whole lot ! I wanted to add the ability to pick on which screen you could launch stuff but never got to it, so that's great. 

I won't have time to merge this until early next week though, but I will and put up a new build with it then. 

There are maybe two or three little tweaks I'd add to this but it's already great as is : 
- maybe only show the menu if there's a secondary monitor at all
- for consistency, use the same menu for the launch fullscreen feature
- mayyyybe add a "Everywhere" option for wallpaper, with the individual screens

But those are minor tweaks that can be added later. Again, thanks a lot for your PR, don't hesitate to ping me early next week if I forgot somehow.

**Comment by asportnoy** [comment]
Hey @glouel, what's the status on this feature? Would love to be able to use the wallpaper option on multiple displays. An option to apply it to all would also be fine with me.

**Comment by glouel** [comment]
Hey @asportnoy 

Because I rewrote the UI this no longer works and I need to rethink the whole thing. I'll try to get on it when I get some vacation around the holidays.

**Comment by asportnoy** [comment]
Thanks!

**Comment by glouel** [comment]
@jdf221 I absolutely apologize for not merging this earlier. I did merge it and will rework it so that it works on the new UI in next beta. Again, really really sorry it took me 2 years to get to it :(

**Comment by glouel** [comment]
Capture d’écran 2023-06-29 à 18 39 32

This looks like this now ;) It's not perfect but it works with the various changes I had made, including restarting at launch on select/all screens.

beta6 is out with the change

**Pull request merged**
